name: Build the website (doesn't deploy - only used for checking syntax)

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: ./actions/build_website
