name: Builds the website (doesn't deploy - only used for checking syntax)

on:  # yamllint disable-line rule:truthy
  push

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install the tutorial_web binary
        run: /usr/bin/env python3 install.py linux
      # Build the website
      - name: Build
        run: ./bin/tutorial_web build -i courses -s ./bin/static -o build -b /tutorial_web_content
